
[package]
name = "azle"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.3.2"
ic-cdk-macros = "0.3.2"
# Boa = "0.13.0"
Boa = { path = "../../../boa/boa", default-features = false }